# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aanshul/Documents/Semester4/Graphics/3D/Assignment2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aanshul/Documents/Semester4/Graphics/3D/Assignment2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aanshul/Documents/Semester4/Graphics/3D/Assignment2/CMakeFiles /home/aanshul/Documents/Semester4/Graphics/3D/Assignment2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aanshul/Documents/Semester4/Graphics/3D/Assignment2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named graphics_asgn1

# Build rule for target.
graphics_asgn1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graphics_asgn1
.PHONY : graphics_asgn1

# fast build rule for target.
graphics_asgn1/fast:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/build
.PHONY : graphics_asgn1/fast

src/ball.o: src/ball.cpp.o

.PHONY : src/ball.o

# target to build an object file
src/ball.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/ball.cpp.o
.PHONY : src/ball.cpp.o

src/ball.i: src/ball.cpp.i

.PHONY : src/ball.i

# target to preprocess a source file
src/ball.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/ball.cpp.i
.PHONY : src/ball.cpp.i

src/ball.s: src/ball.cpp.s

.PHONY : src/ball.s

# target to generate assembly for a file
src/ball.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/ball.cpp.s
.PHONY : src/ball.cpp.s

src/barrel.o: src/barrel.cpp.o

.PHONY : src/barrel.o

# target to build an object file
src/barrel.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/barrel.cpp.o
.PHONY : src/barrel.cpp.o

src/barrel.i: src/barrel.cpp.i

.PHONY : src/barrel.i

# target to preprocess a source file
src/barrel.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/barrel.cpp.i
.PHONY : src/barrel.cpp.i

src/barrel.s: src/barrel.cpp.s

.PHONY : src/barrel.s

# target to generate assembly for a file
src/barrel.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/barrel.cpp.s
.PHONY : src/barrel.cpp.s

src/boat.o: src/boat.cpp.o

.PHONY : src/boat.o

# target to build an object file
src/boat.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/boat.cpp.o
.PHONY : src/boat.cpp.o

src/boat.i: src/boat.cpp.i

.PHONY : src/boat.i

# target to preprocess a source file
src/boat.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/boat.cpp.i
.PHONY : src/boat.cpp.i

src/boat.s: src/boat.cpp.s

.PHONY : src/boat.s

# target to generate assembly for a file
src/boat.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/boat.cpp.s
.PHONY : src/boat.cpp.s

src/boss.o: src/boss.cpp.o

.PHONY : src/boss.o

# target to build an object file
src/boss.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/boss.cpp.o
.PHONY : src/boss.cpp.o

src/boss.i: src/boss.cpp.i

.PHONY : src/boss.i

# target to preprocess a source file
src/boss.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/boss.cpp.i
.PHONY : src/boss.cpp.i

src/boss.s: src/boss.cpp.s

.PHONY : src/boss.s

# target to generate assembly for a file
src/boss.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/boss.cpp.s
.PHONY : src/boss.cpp.s

src/cannon.o: src/cannon.cpp.o

.PHONY : src/cannon.o

# target to build an object file
src/cannon.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/cannon.cpp.o
.PHONY : src/cannon.cpp.o

src/cannon.i: src/cannon.cpp.i

.PHONY : src/cannon.i

# target to preprocess a source file
src/cannon.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/cannon.cpp.i
.PHONY : src/cannon.cpp.i

src/cannon.s: src/cannon.cpp.s

.PHONY : src/cannon.s

# target to generate assembly for a file
src/cannon.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/cannon.cpp.s
.PHONY : src/cannon.cpp.s

src/color.o: src/color.cpp.o

.PHONY : src/color.o

# target to build an object file
src/color.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/color.cpp.o
.PHONY : src/color.cpp.o

src/color.i: src/color.cpp.i

.PHONY : src/color.i

# target to preprocess a source file
src/color.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/color.cpp.i
.PHONY : src/color.cpp.i

src/color.s: src/color.cpp.s

.PHONY : src/color.s

# target to generate assembly for a file
src/color.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/color.cpp.s
.PHONY : src/color.cpp.s

src/diamond.o: src/diamond.cpp.o

.PHONY : src/diamond.o

# target to build an object file
src/diamond.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/diamond.cpp.o
.PHONY : src/diamond.cpp.o

src/diamond.i: src/diamond.cpp.i

.PHONY : src/diamond.i

# target to preprocess a source file
src/diamond.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/diamond.cpp.i
.PHONY : src/diamond.cpp.i

src/diamond.s: src/diamond.cpp.s

.PHONY : src/diamond.s

# target to generate assembly for a file
src/diamond.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/diamond.cpp.s
.PHONY : src/diamond.cpp.s

src/gift.o: src/gift.cpp.o

.PHONY : src/gift.o

# target to build an object file
src/gift.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/gift.cpp.o
.PHONY : src/gift.cpp.o

src/gift.i: src/gift.cpp.i

.PHONY : src/gift.i

# target to preprocess a source file
src/gift.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/gift.cpp.i
.PHONY : src/gift.cpp.i

src/gift.s: src/gift.cpp.s

.PHONY : src/gift.s

# target to generate assembly for a file
src/gift.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/gift.cpp.s
.PHONY : src/gift.cpp.s

src/input.o: src/input.cpp.o

.PHONY : src/input.o

# target to build an object file
src/input.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/input.cpp.o
.PHONY : src/input.cpp.o

src/input.i: src/input.cpp.i

.PHONY : src/input.i

# target to preprocess a source file
src/input.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/input.cpp.i
.PHONY : src/input.cpp.i

src/input.s: src/input.cpp.s

.PHONY : src/input.s

# target to generate assembly for a file
src/input.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/input.cpp.s
.PHONY : src/input.cpp.s

src/island.o: src/island.cpp.o

.PHONY : src/island.o

# target to build an object file
src/island.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/island.cpp.o
.PHONY : src/island.cpp.o

src/island.i: src/island.cpp.i

.PHONY : src/island.i

# target to preprocess a source file
src/island.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/island.cpp.i
.PHONY : src/island.cpp.i

src/island.s: src/island.cpp.s

.PHONY : src/island.s

# target to generate assembly for a file
src/island.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/island.cpp.s
.PHONY : src/island.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/man.o: src/man.cpp.o

.PHONY : src/man.o

# target to build an object file
src/man.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/man.cpp.o
.PHONY : src/man.cpp.o

src/man.i: src/man.cpp.i

.PHONY : src/man.i

# target to preprocess a source file
src/man.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/man.cpp.i
.PHONY : src/man.cpp.i

src/man.s: src/man.cpp.s

.PHONY : src/man.s

# target to generate assembly for a file
src/man.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/man.cpp.s
.PHONY : src/man.cpp.s

src/monster.o: src/monster.cpp.o

.PHONY : src/monster.o

# target to build an object file
src/monster.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/monster.cpp.o
.PHONY : src/monster.cpp.o

src/monster.i: src/monster.cpp.i

.PHONY : src/monster.i

# target to preprocess a source file
src/monster.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/monster.cpp.i
.PHONY : src/monster.cpp.i

src/monster.s: src/monster.cpp.s

.PHONY : src/monster.s

# target to generate assembly for a file
src/monster.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/monster.cpp.s
.PHONY : src/monster.cpp.s

src/nonedit.o: src/nonedit.cpp.o

.PHONY : src/nonedit.o

# target to build an object file
src/nonedit.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/nonedit.cpp.o
.PHONY : src/nonedit.cpp.o

src/nonedit.i: src/nonedit.cpp.i

.PHONY : src/nonedit.i

# target to preprocess a source file
src/nonedit.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/nonedit.cpp.i
.PHONY : src/nonedit.cpp.i

src/nonedit.s: src/nonedit.cpp.s

.PHONY : src/nonedit.s

# target to generate assembly for a file
src/nonedit.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/nonedit.cpp.s
.PHONY : src/nonedit.cpp.s

src/ocean.o: src/ocean.cpp.o

.PHONY : src/ocean.o

# target to build an object file
src/ocean.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/ocean.cpp.o
.PHONY : src/ocean.cpp.o

src/ocean.i: src/ocean.cpp.i

.PHONY : src/ocean.i

# target to preprocess a source file
src/ocean.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/ocean.cpp.i
.PHONY : src/ocean.cpp.i

src/ocean.s: src/ocean.cpp.s

.PHONY : src/ocean.s

# target to generate assembly for a file
src/ocean.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/ocean.cpp.s
.PHONY : src/ocean.cpp.s

src/other_handlers.o: src/other_handlers.cpp.o

.PHONY : src/other_handlers.o

# target to build an object file
src/other_handlers.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/other_handlers.cpp.o
.PHONY : src/other_handlers.cpp.o

src/other_handlers.i: src/other_handlers.cpp.i

.PHONY : src/other_handlers.i

# target to preprocess a source file
src/other_handlers.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/other_handlers.cpp.i
.PHONY : src/other_handlers.cpp.i

src/other_handlers.s: src/other_handlers.cpp.s

.PHONY : src/other_handlers.s

# target to generate assembly for a file
src/other_handlers.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/other_handlers.cpp.s
.PHONY : src/other_handlers.cpp.s

src/power.o: src/power.cpp.o

.PHONY : src/power.o

# target to build an object file
src/power.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/power.cpp.o
.PHONY : src/power.cpp.o

src/power.i: src/power.cpp.i

.PHONY : src/power.i

# target to preprocess a source file
src/power.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/power.cpp.i
.PHONY : src/power.cpp.i

src/power.s: src/power.cpp.s

.PHONY : src/power.s

# target to generate assembly for a file
src/power.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/power.cpp.s
.PHONY : src/power.cpp.s

src/rock.o: src/rock.cpp.o

.PHONY : src/rock.o

# target to build an object file
src/rock.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/rock.cpp.o
.PHONY : src/rock.cpp.o

src/rock.i: src/rock.cpp.i

.PHONY : src/rock.i

# target to preprocess a source file
src/rock.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/rock.cpp.i
.PHONY : src/rock.cpp.i

src/rock.s: src/rock.cpp.s

.PHONY : src/rock.s

# target to generate assembly for a file
src/rock.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/rock.cpp.s
.PHONY : src/rock.cpp.s

src/sail.o: src/sail.cpp.o

.PHONY : src/sail.o

# target to build an object file
src/sail.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/sail.cpp.o
.PHONY : src/sail.cpp.o

src/sail.i: src/sail.cpp.i

.PHONY : src/sail.i

# target to preprocess a source file
src/sail.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/sail.cpp.i
.PHONY : src/sail.cpp.i

src/sail.s: src/sail.cpp.s

.PHONY : src/sail.s

# target to generate assembly for a file
src/sail.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/sail.cpp.s
.PHONY : src/sail.cpp.s

src/timer.o: src/timer.cpp.o

.PHONY : src/timer.o

# target to build an object file
src/timer.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/timer.cpp.o
.PHONY : src/timer.cpp.o

src/timer.i: src/timer.cpp.i

.PHONY : src/timer.i

# target to preprocess a source file
src/timer.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/timer.cpp.i
.PHONY : src/timer.cpp.i

src/timer.s: src/timer.cpp.s

.PHONY : src/timer.s

# target to generate assembly for a file
src/timer.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/timer.cpp.s
.PHONY : src/timer.cpp.s

src/tree.o: src/tree.cpp.o

.PHONY : src/tree.o

# target to build an object file
src/tree.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/tree.cpp.o
.PHONY : src/tree.cpp.o

src/tree.i: src/tree.cpp.i

.PHONY : src/tree.i

# target to preprocess a source file
src/tree.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/tree.cpp.i
.PHONY : src/tree.cpp.i

src/tree.s: src/tree.cpp.s

.PHONY : src/tree.s

# target to generate assembly for a file
src/tree.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/tree.cpp.s
.PHONY : src/tree.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... graphics_asgn1"
	@echo "... src/ball.o"
	@echo "... src/ball.i"
	@echo "... src/ball.s"
	@echo "... src/barrel.o"
	@echo "... src/barrel.i"
	@echo "... src/barrel.s"
	@echo "... src/boat.o"
	@echo "... src/boat.i"
	@echo "... src/boat.s"
	@echo "... src/boss.o"
	@echo "... src/boss.i"
	@echo "... src/boss.s"
	@echo "... src/cannon.o"
	@echo "... src/cannon.i"
	@echo "... src/cannon.s"
	@echo "... src/color.o"
	@echo "... src/color.i"
	@echo "... src/color.s"
	@echo "... src/diamond.o"
	@echo "... src/diamond.i"
	@echo "... src/diamond.s"
	@echo "... src/gift.o"
	@echo "... src/gift.i"
	@echo "... src/gift.s"
	@echo "... src/input.o"
	@echo "... src/input.i"
	@echo "... src/input.s"
	@echo "... src/island.o"
	@echo "... src/island.i"
	@echo "... src/island.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/man.o"
	@echo "... src/man.i"
	@echo "... src/man.s"
	@echo "... src/monster.o"
	@echo "... src/monster.i"
	@echo "... src/monster.s"
	@echo "... src/nonedit.o"
	@echo "... src/nonedit.i"
	@echo "... src/nonedit.s"
	@echo "... src/ocean.o"
	@echo "... src/ocean.i"
	@echo "... src/ocean.s"
	@echo "... src/other_handlers.o"
	@echo "... src/other_handlers.i"
	@echo "... src/other_handlers.s"
	@echo "... src/power.o"
	@echo "... src/power.i"
	@echo "... src/power.s"
	@echo "... src/rock.o"
	@echo "... src/rock.i"
	@echo "... src/rock.s"
	@echo "... src/sail.o"
	@echo "... src/sail.i"
	@echo "... src/sail.s"
	@echo "... src/timer.o"
	@echo "... src/timer.i"
	@echo "... src/timer.s"
	@echo "... src/tree.o"
	@echo "... src/tree.i"
	@echo "... src/tree.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

